name: Ruijie_RG_X60-NEW

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  actions: read

jobs:
  Build:
    uses: ./.github/workflows/Build-Release.yml
    permissions:
      contents: write
      actions: write
    with:
      CONFIG_FILE: configs/ruijie-rg-x60-new.config
      FIRMWARE_TAG: Ruijie_RG_X60-NEW
