name: Trigger-All-Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 5"

permissions:
  contents: read
  actions: read

jobs:
  Ruijie_RG_X60-NEW:
    uses: ./.github/workflows/Ruijie_RG_X60-NEW.yml
    permissions:
      contents: write
      actions: write
#  Netcore_N60-PRO:
#    uses: ./.github/workflows/Netcore_N60-PRO.yml
#    permissions:
#      contents: write
#      actions: write
